### ISSUE TITLE
pip2nix fails on django-leaflet

### ISSUE THREAD

**Issue by LucianU** [datakurre/pip2nix#6]
I run `pip2nix` on a requirements file that contains django-leaflet. The command fails with:

```
Collecting django-leaflet==0.24.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/86/44/869968fdef933502a5268ef7ea695b5fb3f26902df4145235342a4da3ae8/django-leaflet-0.24.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ng/6k6fftj54h1602l6ns0q98mm0000gn/T/pip-install-k78ho01o/django-leaflet/
```

**Comment by datakurre** [comment]
@LucianU Thanks.

It seems that because I have only used pip2nix within nix-shell, I have never seen this before myself. Yet, if I install pip2nix with nix-env, I get can get this. (I've been kind of waiting to get some response from the original authors to get maintenance rights for the pypi version and then polish everything for a new release.)

A current workaround is to run nix-shell in a cloned pip2nix repository and use pip2nix within that shell.

Yet, now that I know this, I should be able to fix this.

**Comment by datakurre** [comment]
@LucianU When you have time, please, try if installation from the current master works for you.

**Comment by LucianU** [comment]
@datakurre, yes it works. Thank you!
